---
# tasks file for ansible-ip

- name: Verify not attempting to take down the current link
  assert:
    that: 
      - 'ansible_default_ipv4.alias is not defined or ip_link_name != ansible_default_ipv4.alias or ip_link_up is not defined or ip_link_up'
    msg: cannot take down {{ ip_link_name }}, ansible is using it

- name: gather link information
  shell: |
    read -r no name flags mtuLbl mtu qdiscLbl qdisc stateLbl state qlenLbl qlen ether <<< \
      $(ip link show {{ ip_link_name }})

    if [ "$state" == UP ]
    then
      up=true
    else
      up=false
    fi

    printf '{ "up":%s, "txqueuelen":%d }\n' "$up" "$qlen"
  register: result
  changed_when: false

- name: store link info
  set_fact:
    ip_current_link: "{{ result.stdout | from_json }}"

- when: ip_link_txqueuelen is defined and ip_link_txqueuelen != none
  block:
    - name: Set {{ ip_link_name }} transmission queue length
      shell: ip link set {{ ip_link_name }} txqueuelen {{ ip_link_txqueuelen }}
      changed_when: ip_link_txqueuelen != ip_current_link.txqueuelen

    - name: Ensure correct transmission queue length on reboot
      lineinfile:
        dest: /etc/rc.local
        regexp: ip link set {{ ip_link_name }} txqueuelen
        line: ip link set {{ ip_link_name }} txqueuelen {{ ip_link_txqueuelen }}
      changed_when: ip_link_txqueuelen != ip_current_link.txqueuelen

- when: ip_link_up is defined and ip_link_up != none
  block:
    - name: Ensure correct state on reboot
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-{{ ip_link_name }}
        regexp: ^ONBOOT=
        line: ONBOOT={{ 'yes' if ip_link_up else 'no' }}    

    - name: Set {{ ip_link_name }} state
      shell: |
        if [ '{{ ip_link_up | lower }}' != '{{ ip_current_link.up }}' ]
        then
          if [ '{{ ip_link_up | lower }}' == true ]
          then
            state=up
          else
            state=down
          fi

          ip link set {{ ip_link_name }} "$state"
        fi
      changed_when: ip_link_up != ip_current_link.up
